pipeline {
    agent any
    tools {
        gradle 'Gradle 7.5.1' 
    }
    stages {
        stage('Build') {
            steps {
                sh 'cd ${path}'
                sh 'ls -la'
            }
        }
        stage('test') {
            steps {
                //sh 'gradle docker'
                echo 'test succesfull'
            }
        }
        stage('Build Docker Image') {
            steps {
                //sh 'gradle docker'
                echo 'succesfull'
            }
        }
        stage('Push Docker Image') {
            steps {
                //sh 'gradle dockerPush'
                echo 'succesfull'
            }
        }
    }
}
