pipeline {
    agent any
    tools {
        gradle 'Gradle 7.5.1' 
    }
    stages {
        stage('Build') {
            steps {
                //sh 'gradle build --info'
                bat 'gradle task'
                bat 'gradle init'
                bat 'gradle wrapper'
                bat './gradlew build'
                bat 'gradle assemble'
            }
        }
        stage('test') {
            steps {
                //sh 'gradle docker'
                echo 'test succesfull'
            }
        }
        stage('Build Docker Image') {
            steps {
                //sh 'gradle docker'
                echo 'succesfull'
            }
        }
        stage('Run Docker Image') {
            steps {
                //sh 'gradle dockerRun'
                echo 'succesfull'
            }
        }
    }
}
