pipeline {
    agent any
    tools {
        gradle 'Gradle 7.5.1' 
    }
    stages {
        stage('Build') {
            steps {
                script{
                sh 'ls -la'
            }
            }
        }
    }
}
